simulation:
  timestep: 0.01
  end_time: 100.0
  graphical: true
  train: false


robot:
  name: bluerov2

  mission:
    waypoints:
      - [0, 0, 0, 0, 0, 0]
      - [5, 0, 0, 0, 0, 0]
      - [0, 5, 0, 0, 0, 0]
      - [0, 0, 5, 0, 0, 0]
      - [0, 0, 0, 0, 0, 0]

  initial_conditions:
    eta: [0, 0, 0, 0, 0, 0]
    nu: [0, 0, 0, 0, 0, 0]

  mass_properties:
    m: 11.5
    rg: [0.0, 0.0, 0.02]
    I0:
      - [0.16, 0.00, 0.00]
      - [0.00, 0.16, 0.00]
      - [0.00, 0.00, 0.16]
    Ma:
      - [5.5, 0, 0, 0, 0, 0]
      - [0, 12.7, 0, 0, 0, 0]
      - [0, 0, 14.57, 0, 0, 0]
      - [0, 0, 0, 0.12, 0, 0]
      - [0, 0, 0, 0, 0.12, 0]
      - [0, 0, 0, 0, 0, 0.12]

  damping:
    Dl:
      - [4.03, 0, 0, 0, 0, 0]
      - [0, 6.22, 0, 0, 0, 0]
      - [0, 0, 5.18, 0, 0, 0]
      - [0, 0, 0, 0.07, 0, 0]
      - [0, 0, 0, 0, 0.07, 0]
      - [0, 0, 0, 0, 0, 0.07]
    Dq:
      - [18.18, 0, 0, 0, 0, 0]
      - [0, 21.66, 0, 0, 0, 0]
      - [0, 0, 36.99, 0, 0, 0]
      - [0, 0, 0, 1.55, 0, 0]
      - [0, 0, 0, 0, 1.55, 0]
      - [0, 0, 0, 0, 0, 1.55]

  thruster:
    T:                          # Thruster allocation matrix (6x8)
      - [0.866, 0.866, -0.839, -0.839, 0.0, 0.0, 0.0, 0.0]
      - [-0.500, 0.500, -0.545, 0.545, 0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
      - [-0.033, 0.033, 0.0359, -0.0359, 0.122, 0.122, -0.117, -0.117]
      - [0.0654, 0.0654, 0.0653, 0.0653, 0.218, -0.218, 0.218, -0.218]
      - [-0.158, 0.158, 0.166, -0.166, 0.0, 0.0, 0.0, 0.0]

    n_thrusters: 8
    thruster_limits: [-35, 45]
    wn: 8
    zeta: 0.9

  controller:
    type: SMC

    eta_tol: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    nu_tol: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    
    smc_params:
      k_smc: [4.0, 4.0, 5.0, 2.0, 2.0, 2.0]
      lambda_smc: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
      phi: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]


# Environment parameters
environment:
  # Open water parameters
  properties:
    gravity: [0.0, 0.0, -9.81]  # Gravity vector in m/s^2
    water_density: 1025.0        # Density of water in kg/m^3
    water_viscosity: 1.0e-3      # Viscosity of water in Pa.s

  current:
    type: time_series  # Options: normal, jet, constant, time_series, depth_profile

    # Type: normal (randomized per axis)
    normal:
      speed: [0.3, 0.1, 0.0]
      std: [0.05, 0.02, 0.01]

    # Type: jet (fully fixed 6D vector)
    jet:
      vector: [0.2, 0.0, 0.0, 0, 0, 0]

    # Type: constant (3D only, angular assumed zero)
    constant:
      vector: [0.1, 0.0, 0.0]

    # Type: time_series (indexed array of 6D vectors)
    time_series:
      - [0.1, 0.0, 0.0, 0, 0, 0]
      - [0.15, 0.05, 0.0, 0, 0, 0]
      - [0.2, 0.0, 0.0, 0, 0, 0]

    # Type: depth_profile (velocity as a function of depth)
    depth_profile:
      - depth: 0
        vector: [0.3, 0.0, 0.0]
      - depth: 10
        vector: [0.1, 0.0, 0.0]
      - depth: 20
        vector: [0.0, 0.0, 0.0]
