simulation:
  timestep: 0.1
  end_time: 10000.0
  graphical: true
  train: false


robot:
  name: nautile

  mission:
    waypoints:
      - [0, 0, 0, 0, 0, 0]
      - [20000000, 0, 0, 0, 0, 0]
      - [0, 20, 0, 0, 0, 0]
      - [0, 0, 20, 0, 0, 0]
      - [0, 0, 0, 0, 0, 0]

  initial_conditions:
    eta: [0, 0, 0, 0, 0, 0]
    nu: [0, 0, 0, 0, 0, 0]

  mass_properties:
    m: 18349
    rg: [-0.013, 0.0, 0.2219]
    I0:
      - [6682, -6.24, 1406]
      - [0.00, 48091, 0.44]
      - [0.00, 0.00, 41660]
    Ma:
      - [6297, 0, 0, 0, 0, 0]
      - [0, 8933, 0, 0, 0, -800]
      - [0, 0, 8933, 0, 800, 0]
      - [0, 0, 0, 700, 0, 0]
      - [0, 0, 800, 0, 1486, 0]
      - [0, -800, 0, 0, 0, 1486]

  damping:
    Dl:
      - [0.0, 0, 0, 0, 0, 0]
      - [0, 0.0, 0, 0, 0, 0]
      - [0, 0, 0.0, 0, 0, 0]
      - [0, 0, 0, 0.0, 0, 0]
      - [0, 0, 0, 0, 10.0, 0]
      - [0, 0, 0, 0, 0, 10.0]
    Dq:
      - [5.0, 0, 0, 0, 0, 0]
      - [0, 15.0, 0, 0, 0, -2]
      - [0, 0, 15.0, 0, 2, -2]
      - [0, 0, 0, 5.0, 0, 0]
      - [0, 0, 2, 0, 40.0, 0]
      - [0, -2, -2, 0, 0, 40.0]

  thruster:
    T:                          # Thruster allocation matrix (6x8)
      - [0.866, 0.866, -0.839, -0.839, 0.0, 0.0, 0.0, 0.0]
      - [-0.500, 0.500, -0.545, 0.545, 0.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
      - [-0.033, 0.033, 0.0359, -0.0359, 0.122, 0.122, -0.117, -0.117]
      - [0.0654, 0.0654, 0.0653, 0.0653, 0.218, -0.218, 0.218, -0.218]
      - [-0.158, 0.158, 0.166, -0.166, 0.0, 0.0, 0.0, 0.0]

    n_thrusters: 8
    thruster_limits: [-3000, 4500]
    wn: 8
    zeta: 0.9

  controller:
    type: SMC

    eta_tol: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    nu_tol: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    
    smc_params:
      k_smc: [4.0, 4.0, 5.0, 2.0, 2.0, 2.0]
      lambda_smc: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
      phi: [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]


# Environment parameters
environment:
  # Open water parameters
  properties:
    gravity: [0.0, 0.0, -9.81]  # Gravity vector in m/s^2
    water_density: 1025.0        # Density of water in kg/m^3
    water_viscosity: 1.0e-3      # Viscosity of water in Pa.s

  current:
    type: time_series  # Options: normal, jet, constant, time_series, depth_profile

    # Type: normal (randomized per axis)
    normal:
      speed: [0.3, 0.1, 0.0]
      std: [0.05, 0.02, 0.01]

    # Type: jet (fully fixed 6D vector)
    jet:
      vector: [0.2, 0.0, 0.0, 0, 0, 0]

    # Type: constant (3D only, angular assumed zero)
    constant:
      vector: [0.1, 0.0, 0.0]

    # Type: time_series (indexed array of 6D vectors)
    time_series:
      - [0.1, 0.0, 0.0, 0, 0, 0]
      - [0.15, 0.05, 0.0, 0, 0, 0]
      - [0.2, 0.0, 0.0, 0, 0, 0]

    # Type: depth_profile (velocity as a function of depth)
    depth_profile:
      - depth: 0
        vector: [0.3, 0.0, 0.0]
      - depth: 10
        vector: [0.1, 0.0, 0.0]
      - depth: 20
        vector: [0.0, 0.0, 0.0]
